### ISSUE TITLE
Same e-mail address can be used more than once.

### ISSUE THREAD

**Issue by gameFace22** [glittergallery/GlitterGallery#189] opened 2015-01-19 18:49 UTC
While registering for an account,we are prompted to give our e-mail address. 
Say my e-mail address is nishaanthguna@gmail.com,I should be able to use it only once.
But in GG,a person will be able to register with same e-mail as many times as possible by tampering the e-mail address.
If I register with nishaanth.guna@gmail.com or nishaan.thguna@gmail.com,it accepts as a valid address(which it should not do)
Check it for yourself!

**Comment by sarupbanskota** [comment] 2015-01-24 21:24
Um, that's intended. Why would you treat them as similar? 

If you were referring to Gmail treating them as the same email address, all email providers don't necessarily follow that. For example, on outlook, sarupbanskota@live.in and sarup.banskota@live.in are different accounts. 

Am I missing something?

**Comment by gameFace22** [comment] 2015-01-25 10:21
Nah.
Actually one person can have multiple accounts with the same e-mail address.
Certain sites(like FB) doesn't allow this.

**Comment by EmilyDirsh** [comment] 2015-02-25 21:52
Ideally the site admin should be able to define rules around acceptable email addresses for registration. I can see use cases for restricting addresses to a specific domain, a set of domains, not allowing + addresses, etc. I'm going to close this as it's not a bug, and open a RFE for site admin registration rules.

**Closed by EmilyDirsh** 2015-02-25 21:52 UTC
