### ISSUE TITLE
uninitialized constant ActionView::CompiledTemplates::FORK

### ISSUE THREAD

**Issue by philippneugebauer** [glittergallery/GlitterGallery#252] opened 2015-03-11 17:37 UTC
When I click on a issue at the issue list, I recieve this error

**Comment by EmilyDirsh** [comment] 2015-03-11 17:42
@philippneugebauer I haven't seen that error before myself - could be a side effect of the gem changes you made. Can you post the traceback?

**Comment by philippneugebauer** [comment] 2015-03-11 18:10
I started from scratch and I still get this error

**Comment by Alwahsh** [comment] 2015-03-11 18:15
yes this is an issue. I can confirm it.
see this line here:
https://github.com/glittergallery/GlitterGallery/blob/master/app/views/issues/show.html.haml#L22
It should be fixed in #240 after my next push to it since it's related to forked projects :)

**Closed** 2015-03-14 17:14 UTC
Labels: bug
